### ISSUE TITLE
.

### ISSUE THREAD

**Issue by gayafio** [YK-Yash/Digital_Hearing_Aid#1]
Hi,

I am getting errors on Matlab with this code.

Error: File: hearingAidF.m Error: File: hearingAidF.m Line: 4 Column: 26
Invalid expression. Check for missing multiplication operator, missing or unbalanced delimiters, or other syntax error. To construct matrices, use brackets instead of parentheses.

this is Line: 4 Column: 26
function y = hearingAidF('late_cafe.wav',6,90,[3000 4000 5000 9000],'new_sound');

please help

**Comment by bclymer-sri** [comment]
MatLab thinks you're trying to declare a function, because you wrote `function y = hearingAidF(`, but it doesn't know how to handle the hardcoded parameters you put in there. 

1. Revert the code to its original form. Undo your hardcoding. 
2. Navigate to the folder in which hearingAidF.m is located
3. In a separate script (_not_ hearingAidF.m), or from the command line, call the function as you were trying:
`hearingAidF('late_cafe.wav',6,90,[3000 4000 5000 9000],'new_sound')`

It's sometimes good to play around with code you don't understand, to gain an understanding. However, based upon your lack of understanding a function call or header, this codebase seems a bit more advanced than your understanding of MatLab; I suggest you sit with someone who has MatLab experience, and can explain this to you.
